**NumPy处理大量数组的效率更高**

In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 26.3 ms, sys: 16.4 ms, total: 42.7 ms
Wall time: 41.9 ms


In [9]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 736 ms, sys: 201 ms, total: 937 ms
Wall time: 963 ms


# 多维数组对象 ndarray

In [19]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 0.54000743,  1.1118009 ,  0.85228074],
       [-1.37988643,  2.14382986,  1.22862503]])

In [20]:
data.shape

(2, 3)

In [21]:
data.dtype

dtype('float64')

## **arange是Python内建函数range的数组版**

In [24]:
range(15)

range(0, 15)

In [26]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## **数组的切片是原数组的视图，所以“切片”并不是复制出来的，任何对视图的修改都会反映到原数组上**

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr_slice = arr[4:7]
arr_slice

array([4, 5, 6])

In [8]:
arr_slice[1] = 123

In [14]:
arr_slice

array([  4, 123,   6])

In [9]:
arr

array([  0,   1,   2,   3,   4, 123,   6,   7,   8,   9])

**如果想要一份数组切片的拷贝而不是一份视图的话，就必须显式地复制这个数组**

In [10]:
arr_copy = arr[4:7].copy()
arr_copy

array([  4, 123,   6])

In [11]:
arr_copy[1] = 987

In [13]:
arr_copy

array([  4, 987,   6])

In [12]:
arr

array([  0,   1,   2,   3,   4, 123,   6,   7,   8,   9])

## 数组的切片和索引

In [15]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**如果索引和切片混用，就可以得到低维度的切片**

In [25]:
# 索引和切片混用
arr2d[:2,2]

array([3, 6])

In [26]:
arr2d[:2,2].shape

(2,)

In [23]:
# 只切片
arr2d[:2,2:3]

array([[3],
       [6]])

In [27]:
arr2d[:2,2:3].shape

(2, 1)